"""initial schema

Revision ID: f2fc58597e81
Revises: 
Create Date: 2026-10-05 12:14:45.326614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.db.triggers import DROP_DDL, TRIGGER_DDL

_ENUM_TYPES = [
    "audience_mode", "auth_provider", "automation_status", "automation_trigger",
    "block_kind", "bounce_type", "campaign_status", "campaign_tier", "change_source",
    "domain_auth_status", "email_event_type", "email_frequency", "email_provider",
    "enrollment_status", "field_type", "import_status", "import_target",
    "membership_status", "message_status", "recipient_status", "segment_match",
    "sender_status", "skip_reason", "step_type", "subscriber_status",
    "subscription_event_type", "suppression_reason", "token_purpose", "user_role",
    "wait_unit",
]

# revision identifiers, used by Alembic.
revision: str = 'f2fc58597e81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Business name used in the email footer'),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.CHAR(length=2), nullable=False, comment='ISO 3166-1 alpha-2'),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False, comment='IANA timezone for scheduling and display (BR-07)'),
    sa.Column('date_format', sa.String(length=20), server_default='DD/MM/YYYY', nullable=False),
    sa.Column('time_format', sa.String(length=5), server_default='24h', nullable=False),
    sa.Column('logo_key', sa.String(length=512), nullable=True, comment='Object-storage key (PREF-08)'),
    sa.Column('brand_color', sa.CHAR(length=7), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True, comment='Set when send-readiness checks first pass (ONB-07, ONB-09)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    op.create_table('custom_fields',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False, comment='Merge-tag key, e.g. company'),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('data_type', sa.Enum('text', 'number', 'date', 'boolean', 'choice', name='field_type'), server_default='text', nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Allowed values for choice fields'),
    sa.Column('show_in_preferences', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='PREF-02'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_custom_fields_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_fields'))
    )
    op.create_index('uq_custom_fields_account_id_field_key', 'custom_fields', ['account_id', 'field_key'], unique=True)
    op.create_table('lists',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('show_in_preferences', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_lists_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lists'))
    )
    op.create_index('uq_lists_account_id_name', 'lists', ['account_id', 'name'], unique=True)
    op.create_table('sending_domains',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('dkim_status', sa.Enum('not_started', 'pending', 'verified', 'failed', name='domain_auth_status'), server_default='not_started', nullable=False),
    sa.Column('spf_status', sa.Enum('not_started', 'pending', 'verified', 'failed', name='domain_auth_status'), server_default='not_started', nullable=False),
    sa.Column('dmarc_status', sa.Enum('not_started', 'pending', 'verified', 'failed', name='domain_auth_status'), server_default='not_started', nullable=False),
    sa.Column('provider_identity', sa.String(length=255), nullable=True, comment='Provider identity reference, e.g. SES identity ARN'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_sending_domains_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sending_domains'))
    )
    op.create_index('uq_sending_domains_account_id_domain', 'sending_domains', ['account_id', 'domain'], unique=True)
    op.create_table('subscribers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True, comment='Customer subscriber number / ID from CSV (SUB-IMP-06)'),
    sa.Column('status', sa.Enum('subscribed', 'unsubscribed', 'suppressed', name='subscriber_status'), server_default='subscribed', nullable=False, comment='Imports never overwrite unsubscribed / suppressed (BR-05)'),
    sa.Column('source', sa.Enum('manual', 'csv_import', 'api', 'preference_center', 'one_click_unsubscribe', 'email_link', 'provider_event', 'automation', name='change_source'), server_default='manual', nullable=False),
    sa.Column('consent_source', sa.String(length=255), nullable=True, comment='SUB-10'),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_ip', postgresql.INET(), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_frequency', sa.Enum('all', 'weekly_digest', 'essential_only', name='email_frequency'), server_default='all', nullable=False, comment='Frequency preference (PREF-09)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_subscribers_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscribers'))
    )
    op.create_index('ix_subscribers_account_id_created_at', 'subscribers', ['account_id', 'created_at'], unique=False)
    op.create_index('ix_subscribers_account_id_external_id', 'subscribers', ['account_id', 'external_id'], unique=False)
    op.create_index('ix_subscribers_account_id_status', 'subscribers', ['account_id', 'status'], unique=False)
    op.create_index('uq_subscribers_account_id_email', 'subscribers', ['account_id', 'email'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_tags_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index('uq_tags_account_id_name', 'tags', ['account_id', 'name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False, comment='Login email, globally unique'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='argon2id; NULL for users who only sign in through an external IdP'),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='user_role'), server_default='owner', nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_users_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_account_id', 'users', ['account_id'], unique=False)
    op.create_table('auth_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Enum('email_verification', 'password_reset', name='token_purpose'), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_tokens_token_hash'))
    )
    op.create_index('ix_auth_tokens_user_id_purpose', 'auth_tokens', ['user_id', 'purpose'], unique=False)
    op.create_table('content_blocks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('header', 'footer', name='block_kind'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Used for new templates; one default per kind'),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_content_blocks_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_content_blocks_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_blocks'))
    )
    op.create_index('ix_content_blocks_account_id_kind', 'content_blocks', ['account_id', 'kind'], unique=False)
    op.create_index('uq_content_blocks_default_per_kind', 'content_blocks', ['account_id', 'kind'], unique=True, postgresql_where=sa.text('is_default AND deleted_at IS NULL'))
    op.create_table('import_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'completed_with_errors', 'failed', name='import_status'), server_default='queued', nullable=False),
    sa.Column('file_key', sa.String(length=512), nullable=False, comment='Object-storage key of the CSV'),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('has_header_row', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='SUB-IMP-03'),
    sa.Column('target_list_id', sa.UUID(), nullable=True),
    sa.Column('update_existing', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Update profile data of existing subscribers; never overrides unsubscribe/suppression'),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('imported_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duplicate_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rejected_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=True, comment='Trace ID across API request, background job and provider events'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_import_jobs_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_import_jobs_created_by_users')),
    sa.ForeignKeyConstraint(['target_list_id'], ['lists.id'], name=op.f('fk_import_jobs_target_list_id_lists'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_jobs'))
    )
    op.create_index('ix_import_jobs_account_id_created_at', 'import_jobs', ['account_id', 'created_at'], unique=False)
    op.create_index('ix_import_jobs_pending', 'import_jobs', ['created_at'], unique=False, postgresql_where=sa.text("status IN ('queued', 'processing')"))
    op.create_table('list_memberships',
    sa.Column('list_id', sa.UUID(), nullable=False),
    sa.Column('subscriber_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'opted_out', name='membership_status'), server_default='active', nullable=False, comment='opted_out keeps history for opt-down (PREF-04)'),
    sa.Column('source', sa.Enum('manual', 'csv_import', 'api', 'preference_center', 'one_click_unsubscribe', 'email_link', 'provider_event', 'automation', name='change_source'), server_default='manual', nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name=op.f('fk_list_memberships_list_id_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], name=op.f('fk_list_memberships_subscriber_id_subscribers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('list_id', 'subscriber_id', name=op.f('pk_list_memberships'))
    )
    op.create_index('ix_list_memberships_list_id_active', 'list_memberships', ['list_id'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('ix_list_memberships_subscriber_id', 'list_memberships', ['subscriber_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('file_key', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True, comment='TMP-10'),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_media_assets_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_media_assets_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets'))
    )
    op.create_index(op.f('ix_media_assets_account_id'), 'media_assets', ['account_id'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('match_type', sa.Enum('all', 'any', name='segment_match'), server_default='all', nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Rules over fields, tags, lists and status'),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_segments_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_segments_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_segments'))
    )
    op.create_index('uq_segments_account_id_name', 'segments', ['account_id', 'name'], unique=True)
    op.create_table('senders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('sending_domain_id', sa.UUID(), nullable=True),
    sa.Column('from_name', sa.String(length=120), nullable=False),
    sa.Column('from_email', postgresql.CITEXT(), nullable=False),
    sa.Column('reply_to_email', postgresql.CITEXT(), nullable=True),
    sa.Column('status', sa.Enum('unverified', 'verification_pending', 'verified', name='sender_status'), server_default='unverified', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_senders_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sending_domain_id'], ['sending_domains.id'], name=op.f('fk_senders_sending_domain_id_sending_domains'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_senders'))
    )
    op.create_index('uq_senders_account_id_from_email', 'senders', ['account_id', 'from_email'], unique=True)
    op.create_table('subscriber_field_values',
    sa.Column('subscriber_id', sa.UUID(), nullable=False),
    sa.Column('custom_field_id', sa.UUID(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Numeric(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(value_text, value_number, value_date, value_bool) <= 1', name=op.f('ck_subscriber_field_values_single_typed_value')),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_fields.id'], name=op.f('fk_subscriber_field_values_custom_field_id_custom_fields'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], name=op.f('fk_subscriber_field_values_subscriber_id_subscribers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscriber_id', 'custom_field_id', name=op.f('pk_subscriber_field_values'))
    )
    op.create_index('ix_subscriber_field_values_field_id_value_text', 'subscriber_field_values', ['custom_field_id', 'value_text'], unique=False)
    op.create_table('subscriber_tags',
    sa.Column('subscriber_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], name=op.f('fk_subscriber_tags_subscriber_id_subscribers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_subscriber_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscriber_id', 'tag_id', name=op.f('pk_subscriber_tags'))
    )
    op.create_index('ix_subscriber_tags_tag_id', 'subscriber_tags', ['tag_id'], unique=False)
    op.create_table('user_identities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('google', 'microsoft', 'auth0', 'cognito', 'oidc', name='auth_provider'), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False, comment='OIDC iss claim'),
    sa.Column('external_subject', sa.String(length=255), nullable=False, comment='OIDC sub claim'),
    sa.Column('email_at_provider', postgresql.CITEXT(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_identities'))
    )
    op.create_index('ix_user_identities_user_id', 'user_identities', ['user_id'], unique=False)
    op.create_index('uq_user_identities_issuer_subject', 'user_identities', ['issuer', 'external_subject'], unique=True)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_user_sessions_refresh_token_hash'))
    )
    op.create_index('ix_user_sessions_user_id_active', 'user_sessions', ['user_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('automations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', name='automation_status'), server_default='draft', nullable=False),
    sa.Column('trigger_type', sa.Enum('list_joined', 'tag_applied', name='automation_trigger'), nullable=False),
    sa.Column('trigger_list_id', sa.UUID(), nullable=True),
    sa.Column('trigger_tag_id', sa.UUID(), nullable=True),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('allow_reentry', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='AUT-09'),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(trigger_type = 'list_joined' AND trigger_list_id IS NOT NULL AND trigger_tag_id IS NULL) OR (trigger_type = 'tag_applied' AND trigger_tag_id IS NOT NULL AND trigger_list_id IS NULL)", name=op.f('ck_automations_trigger_target_matches_type')),
    sa.CheckConstraint("status <> 'active' OR sender_id IS NOT NULL", name=op.f('ck_automations_active_has_sender')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_automations_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_automations_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['senders.id'], name=op.f('fk_automations_sender_id_senders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trigger_list_id'], ['lists.id'], name=op.f('fk_automations_trigger_list_id_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_tag_id'], ['tags.id'], name=op.f('fk_automations_trigger_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automations'))
    )
    op.create_index('ix_automations_account_id_status', 'automations', ['account_id', 'status'], unique=False)
    op.create_index('ix_automations_active_trigger_list', 'automations', ['trigger_list_id'], unique=False, postgresql_where=sa.text("status = 'active' AND trigger_list_id IS NOT NULL"))
    op.create_index('ix_automations_active_trigger_tag', 'automations', ['trigger_tag_id'], unique=False, postgresql_where=sa.text("status = 'active' AND trigger_tag_id IS NOT NULL"))
    op.create_table('import_column_mappings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('import_job_id', sa.UUID(), nullable=False),
    sa.Column('column_index', sa.Integer(), nullable=False),
    sa.Column('source_header', sa.String(length=255), nullable=True),
    sa.Column('sample_value', sa.Text(), nullable=True),
    sa.Column('target', sa.Enum('email', 'first_name', 'last_name', 'external_id', 'custom_field', 'ignore', name='import_target'), nullable=False),
    sa.Column('custom_field_id', sa.UUID(), nullable=True, comment='Set when target = custom_field'),
    sa.CheckConstraint("(target = 'custom_field') = (custom_field_id IS NOT NULL)", name=op.f('ck_import_column_mappings_custom_field_target')),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_fields.id'], name=op.f('fk_import_column_mappings_custom_field_id_custom_fields'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], name=op.f('fk_import_column_mappings_import_job_id_import_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_column_mappings'))
    )
    op.create_index('uq_import_column_mappings_job_id_column_index', 'import_column_mappings', ['import_job_id', 'column_index'], unique=True)
    op.create_table('import_row_errors',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('import_job_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=False, comment='invalid_email, missing_email, duplicate_in_file, suppressed'),
    sa.Column('raw_row', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], name=op.f('fk_import_row_errors_import_job_id_import_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_row_errors'))
    )
    op.create_index('ix_import_row_errors_import_job_id', 'import_row_errors', ['import_job_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('preheader', sa.String(length=255), nullable=True),
    sa.Column('header_block_id', sa.UUID(), nullable=True),
    sa.Column('footer_block_id', sa.UUID(), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Body blocks: text, image, button, divider, spacer (TMP-02)'),
    sa.Column('html', sa.Text(), nullable=True, comment='Rendered responsive HTML'),
    sa.Column('plain_text', sa.Text(), nullable=True, comment='Plain-text fallback (TMP-11)'),
    sa.Column('duplicated_from_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_templates_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_templates_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicated_from_id'], ['templates.id'], name=op.f('fk_templates_duplicated_from_id_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['footer_block_id'], ['content_blocks.id'], name=op.f('fk_templates_footer_block_id_content_blocks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['header_block_id'], ['content_blocks.id'], name=op.f('fk_templates_header_block_id_content_blocks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates'))
    )
    op.create_index('ix_templates_account_id_name', 'templates', ['account_id', 'name'], unique=False)
    op.create_table('automation_steps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('automation_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('email', 'wait', name='step_type'), nullable=False),
    sa.Column('wait_amount', sa.Integer(), nullable=True),
    sa.Column('wait_unit', sa.Enum('hours', 'days', name='wait_unit'), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('preheader', sa.String(length=255), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(step_type = 'wait' AND wait_amount > 0 AND wait_unit IS NOT NULL AND template_id IS NULL AND content_json IS NULL) OR (step_type = 'email' AND wait_amount IS NULL AND wait_unit IS NULL AND (template_id IS NOT NULL OR content_json IS NOT NULL))", name=op.f('ck_automation_steps_step_fields_match_type')),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], name=op.f('fk_automation_steps_automation_id_automations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_automation_steps_template_id_templates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_steps'))
    )
    op.create_index('uq_automation_steps_automation_id_position', 'automation_steps', ['automation_id', 'position'], unique=True)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Internal name (CMP-01)'),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'sending', 'sent', 'partially_failed', 'failed', 'cancelled', name='campaign_status'), server_default='draft', nullable=False),
    sa.Column('tier', sa.Enum('regular', 'digest', 'essential', name='campaign_tier'), server_default='regular', nullable=False, comment='Matched against subscribers.email_frequency (PREF-09)'),
    sa.Column('topic_list_id', sa.UUID(), nullable=True, comment='Topic this campaign counts as for preference-center opt-outs. Applies even when the audience is a segment, tag, or individual subscriber, not just a list (schema-v1.md section 4)'),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True, comment='Template it started from; content is copied into this row'),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('preheader', sa.String(length=255), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('plain_text', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True, comment='UTC; entered in account timezone (CMP-09)'),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='Final pre-send confirmation (CMP-08)'),
    sa.Column('audience_frozen_at', sa.DateTime(timezone=True), nullable=True, comment='campaign_recipients written; audience fixed'),
    sa.Column('sending_started_at', sa.DateTime(timezone=True), nullable=True, comment='Content and audience immutable from here (BR-04)'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eligible_count', sa.Integer(), nullable=True, comment='Recipients with status pending/queued after freeze (CMP-05)'),
    sa.Column('duplicated_from_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=True, comment='Trace ID across API request, background job and provider events'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'scheduled' OR scheduled_at IS NOT NULL", name=op.f('ck_campaigns_scheduled_has_time')),
    sa.CheckConstraint("status NOT IN ('scheduled', 'sending', 'sent', 'partially_failed', 'failed') OR (sender_id IS NOT NULL AND confirmed_at IS NOT NULL)", name=op.f('ck_campaigns_confirmed_before_send')),
    sa.CheckConstraint("status NOT IN ('sending', 'sent', 'partially_failed', 'failed') OR (audience_frozen_at IS NOT NULL AND sending_started_at IS NOT NULL)", name=op.f('ck_campaigns_frozen_before_send')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_campaigns_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_campaigns_confirmed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_campaigns_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicated_from_id'], ['campaigns.id'], name=op.f('fk_campaigns_duplicated_from_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['senders.id'], name=op.f('fk_campaigns_sender_id_senders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_campaigns_template_id_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_list_id'], ['lists.id'], name=op.f('fk_campaigns_topic_list_id_lists'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index('ix_campaigns_account_id_created_at', 'campaigns', ['account_id', 'created_at'], unique=False)
    op.create_index('ix_campaigns_account_id_status', 'campaigns', ['account_id', 'status'], unique=False)
    op.create_index('ix_campaigns_due', 'campaigns', ['scheduled_at'], unique=False, postgresql_where=sa.text("status = 'scheduled'"))
    op.create_index('ix_campaigns_topic_list_id', 'campaigns', ['topic_list_id'], unique=False, postgresql_where=sa.text('topic_list_id IS NOT NULL'))
    op.create_table('automation_enrollments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('automation_id', sa.UUID(), nullable=False),
    sa.Column('subscriber_id', sa.UUID(), nullable=False),
    sa.Column('current_step_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'exited', name='enrollment_status'), server_default='active', nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True, comment='Worker picks up due steps'),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True, comment='e.g. unsubscribed, suppressed, automation_paused'),
    sa.CheckConstraint("status <> 'active' OR next_run_at IS NOT NULL", name=op.f('ck_automation_enrollments_active_has_next_run')),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], name=op.f('fk_automation_enrollments_automation_id_automations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_step_id'], ['automation_steps.id'], name=op.f('fk_automation_enrollments_current_step_id_automation_steps'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], name=op.f('fk_automation_enrollments_subscriber_id_subscribers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_enrollments'))
    )
    op.create_index('ix_automation_enrollments_current_step_id', 'automation_enrollments', ['current_step_id'], unique=False)
    op.create_index('ix_automation_enrollments_due', 'automation_enrollments', ['next_run_at'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('ix_automation_enrollments_subscriber_id', 'automation_enrollments', ['subscriber_id'], unique=False)
    op.create_index('uq_automation_enrollments_automation_id_subscriber_id', 'automation_enrollments', ['automation_id', 'subscriber_id'], unique=True)
    op.create_table('campaign_audiences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('include', 'exclude', name='audience_mode'), server_default='include', nullable=False),
    sa.Column('list_id', sa.UUID(), nullable=True),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.Column('tag_id', sa.UUID(), nullable=True),
    sa.Column('subscriber_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('num_nonnulls(list_id, segment_id, tag_id, subscriber_id) = 1', name=op.f('ck_campaign_audiences_exactly_one_target')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_audiences_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name=op.f('fk_campaign_audiences_list_id_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], name=op.f('fk_campaign_audiences_segment_id_segments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], name=op.f('fk_campaign_audiences_subscriber_id_subscribers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_campaign_audiences_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_audiences'))
    )
    op.create_index('ix_campaign_audiences_campaign_id', 'campaign_audiences', ['campaign_id'], unique=False)
    op.create_index('ix_campaign_audiences_list_id', 'campaign_audiences', ['list_id'], unique=False, postgresql_where=sa.text('list_id IS NOT NULL'))
    op.create_index('ix_campaign_audiences_segment_id', 'campaign_audiences', ['segment_id'], unique=False, postgresql_where=sa.text('segment_id IS NOT NULL'))
    op.create_index('ix_campaign_audiences_subscriber_id', 'campaign_audiences', ['subscriber_id'], unique=False, postgresql_where=sa.text('subscriber_id IS NOT NULL'))
    op.create_index('ix_campaign_audiences_tag_id', 'campaign_audiences', ['tag_id'], unique=False, postgresql_where=sa.text('tag_id IS NOT NULL'))
    op.create_table('campaign_links',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_links_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_links'))
    )
    op.create_index('ix_campaign_links_campaign_id', 'campaign_links', ['campaign_id'], unique=False)
    op.create_table('campaign_stats',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('recipients', sa.Integer(), server_default='0', nullable=False, comment='Frozen, not skipped'),
    sa.Column('skipped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sent', sa.Integer(), server_default='0', nullable=False, comment='Accepted by the provider'),
    sa.Column('delivered', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hard_bounces', sa.Integer(), server_default='0', nullable=False),
    sa.Column('soft_bounces', sa.Integer(), server_default='0', nullable=False),
    sa.Column('complaints', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unique_opens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unique_clicks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unsubscribes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failures', sa.Integer(), server_default='0', nullable=False, comment='failed + rejected'),
    sa.Column('last_event_id', sa.BigInteger(), nullable=True, comment='Highest email_events.id included'),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_stats_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', name=op.f('pk_campaign_stats'))
    )
    op.create_table('test_sends',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('sent_by', sa.UUID(), nullable=False),
    sa.Column('to_emails', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_test_sends_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], name=op.f('fk_test_sends_sent_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_sends'))
    )
    op.create_index(op.f('ix_test_sends_campaign_id'), 'test_sends', ['campaign_id'], unique=False)
    op.create_table('campaign_recipients',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('subscriber_id', sa.UUID(), nullable=True, comment='NULL only if the subscriber was deleted later'),
    sa.Column('email', postgresql.CITEXT(), nullable=False, comment='Snapshot at freeze time'),
    sa.Column('merge_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Snapshot of personalization fields at freeze time'),
    sa.Column('matched_audience_id', sa.UUID(), nullable=True, comment='First include rule that selected this person'),
    sa.Column('status', sa.Enum('pending', 'queued', 'skipped', 'cancelled', name='recipient_status'), server_default='pending', nullable=False),
    sa.Column('skip_reason', sa.Enum('unsubscribed', 'suppressed', 'list_opted_out', 'frequency_preference', 'excluded_by_rule', 'invalid_email', name='skip_reason'), nullable=True),
    sa.Column('frozen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'skipped') = (skip_reason IS NOT NULL)", name=op.f('ck_campaign_recipients_skip_reason_iff_skipped')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_recipients_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_audience_id'], ['campaign_audiences.id'], name=op.f('fk_campaign_recipients_matched_audience_id_campaign_audiences'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], name=op.f('fk_campaign_recipients_subscriber_id_subscribers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_recipients'))
    )
    op.create_index('ix_campaign_recipients_campaign_id_status', 'campaign_recipients', ['campaign_id', 'status'], unique=False)
    op.create_index('ix_campaign_recipients_subscriber_id', 'campaign_recipients', ['subscriber_id'], unique=False)
    op.create_index('uq_campaign_recipients_campaign_id_email', 'campaign_recipients', ['campaign_id', 'email'], unique=True)
    op.create_table('email_messages',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('subscriber_id', sa.UUID(), nullable=True),
    sa.Column('email', postgresql.CITEXT(), nullable=False, comment='Recipient snapshot'),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('campaign_recipient_id', sa.BigInteger(), nullable=True),
    sa.Column('automation_id', sa.UUID(), nullable=True),
    sa.Column('automation_step_id', sa.UUID(), nullable=True),
    sa.Column('enrollment_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'submitting', 'accepted', 'delivered', 'soft_bounced', 'bounced', 'complained', 'rejected', 'failed', 'cancelled', name='message_status'), server_default='queued', nullable=False),
    sa.Column('provider', sa.Enum('ses', 'tracking', name='email_provider'), server_default='ses', nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True, comment='Set when the provider accepts the message'),
    sa.Column('attempt_count', sa.SmallInteger(), server_default='0', nullable=False, comment='Bounded retries (CMP-14)'),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True, comment='Backoff for temporary provider failures'),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bounced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('complained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=True, comment='Trace ID across API request, background job and provider events'),
    sa.CheckConstraint("status <> 'delivered' OR delivered_at IS NOT NULL", name=op.f('ck_email_messages_delivered_has_timestamp')),
    sa.CheckConstraint("status NOT IN ('accepted', 'delivered', 'soft_bounced', 'bounced', 'complained', 'rejected') OR (provider_message_id IS NOT NULL AND accepted_at IS NOT NULL)", name=op.f('ck_email_messages_accepted_has_provider_id')),
    sa.CheckConstraint('(campaign_id IS NOT NULL AND campaign_recipient_id IS NOT NULL AND automation_id IS NULL) OR (automation_id IS NOT NULL AND campaign_id IS NULL AND campaign_recipient_id IS NULL)', name=op.f('ck_email_messages_one_origin')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_email_messages_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], name=op.f('fk_email_messages_automation_id_automations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['automation_step_id'], ['automation_steps.id'], name=op.f('fk_email_messages_automation_step_id_automation_steps'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_email_messages_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_recipient_id'], ['campaign_recipients.id'], name=op.f('fk_email_messages_campaign_recipient_id_campaign_recipients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['automation_enrollments.id'], name=op.f('fk_email_messages_enrollment_id_automation_enrollments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], name=op.f('fk_email_messages_subscriber_id_subscribers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_messages'))
    )
    op.create_index('ix_email_messages_account_id_queued_at', 'email_messages', ['account_id', 'queued_at'], unique=False)
    op.create_index('ix_email_messages_automation_id', 'email_messages', ['automation_id'], unique=False, postgresql_where=sa.text('automation_id IS NOT NULL'))
    op.create_index('ix_email_messages_automation_step_id', 'email_messages', ['automation_step_id'], unique=False, postgresql_where=sa.text('automation_step_id IS NOT NULL'))
    op.create_index('ix_email_messages_campaign_id_status', 'email_messages', ['campaign_id', 'status'], unique=False)
    op.create_index('ix_email_messages_pending', 'email_messages', ['queued_at'], unique=False, postgresql_where=sa.text("status IN ('queued', 'submitting')"))
    op.create_index('ix_email_messages_subscriber_id', 'email_messages', ['subscriber_id'], unique=False)
    op.create_index('uq_email_messages_campaign_recipient_id', 'email_messages', ['campaign_recipient_id'], unique=True, postgresql_where=sa.text('campaign_recipient_id IS NOT NULL'))
    op.create_index('uq_email_messages_enrollment_id_step_id', 'email_messages', ['enrollment_id', 'automation_step_id'], unique=True, postgresql_where=sa.text('enrollment_id IS NOT NULL'))
    op.create_index('uq_email_messages_provider_message_id', 'email_messages', ['provider', 'provider_message_id'], unique=True, postgresql_where=sa.text('provider_message_id IS NOT NULL'))
    op.create_table('email_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True, comment='NULL only if the provider reports an unknown message'),
    sa.Column('campaign_id', sa.UUID(), nullable=True, comment='Copied from the message so campaign reports avoid a join'),
    sa.Column('provider', sa.Enum('ses', 'tracking', name='email_provider'), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False, comment="Provider's event ID; dedupes webhook redeliveries"),
    sa.Column('event_type', sa.Enum('send', 'delivery', 'delivery_delay', 'bounce', 'complaint', 'reject', 'open', 'click', 'unsubscribe', name='email_event_type'), nullable=False),
    sa.Column('bounce_type', sa.Enum('permanent', 'transient', 'undetermined', name='bounce_type'), nullable=True),
    sa.Column('link_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=True, comment='Trace ID across API request, background job and provider events'),
    sa.CheckConstraint("event_type = 'bounce' OR bounce_type IS NULL", name=op.f('ck_email_events_bounce_type_only_on_bounce')),
    sa.CheckConstraint("event_type = 'click' OR link_id IS NULL", name=op.f('ck_email_events_link_only_on_click')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_email_events_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_email_events_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['campaign_links.id'], name=op.f('fk_email_events_link_id_campaign_links'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['email_messages.id'], name=op.f('fk_email_events_message_id_email_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_events'))
    )
    op.create_index('ix_email_events_account_id_event_type_occurred_at', 'email_events', ['account_id', 'event_type', 'occurred_at'], unique=False)
    op.create_index('ix_email_events_campaign_id_event_type', 'email_events', ['campaign_id', 'event_type'], unique=False)
    op.create_index('ix_email_events_link_id', 'email_events', ['link_id'], unique=False, postgresql_where=sa.text('link_id IS NOT NULL'))
    op.create_index('ix_email_events_message_id', 'email_events', ['message_id'], unique=False)
    op.create_index('uq_email_events_provider_event_id', 'email_events', ['provider', 'provider_event_id'], unique=True)
    op.create_table('subscription_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('subscriber_id', sa.UUID(), nullable=True),
    sa.Column('email', postgresql.CITEXT(), nullable=False, comment='Snapshot, kept if subscriber is deleted'),
    sa.Column('event_type', sa.Enum('subscribed', 'unsubscribed', 'resubscribed', 'list_opt_in', 'list_opt_out', 'profile_updated', 'suppressed', name='subscription_event_type'), nullable=False),
    sa.Column('list_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'csv_import', 'api', 'preference_center', 'one_click_unsubscribe', 'email_link', 'provider_event', 'automation', name='change_source'), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=True, comment='Trace ID across API request, background job and provider events'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_subscription_events_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_subscription_events_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name=op.f('fk_subscription_events_list_id_lists'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['email_messages.id'], name=op.f('fk_subscription_events_message_id_email_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], name=op.f('fk_subscription_events_subscriber_id_subscribers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_events'))
    )
    op.create_index('ix_subscription_events_account_id_occurred_at', 'subscription_events', ['account_id', 'occurred_at'], unique=False)
    op.create_index('ix_subscription_events_campaign_id', 'subscription_events', ['campaign_id'], unique=False, postgresql_where=sa.text('campaign_id IS NOT NULL'))
    op.create_index('ix_subscription_events_list_id', 'subscription_events', ['list_id'], unique=False, postgresql_where=sa.text('list_id IS NOT NULL'))
    op.create_index('ix_subscription_events_message_id', 'subscription_events', ['message_id'], unique=False, postgresql_where=sa.text('message_id IS NOT NULL'))
    op.create_index('ix_subscription_events_subscriber_id_occurred_at', 'subscription_events', ['subscriber_id', 'occurred_at'], unique=False)
    op.create_table('suppressions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('reason', sa.Enum('hard_bounce', 'complaint', 'unsubscribe', 'manual', name='suppression_reason'), nullable=False),
    sa.Column('source', sa.Enum('manual', 'csv_import', 'api', 'preference_center', 'one_click_unsubscribe', 'email_link', 'provider_event', 'automation', name='change_source'), nullable=False),
    sa.Column('email_event_id', sa.BigInteger(), nullable=True, comment='Bounce / complaint event that caused it'),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('lifted_at', sa.DateTime(timezone=True), nullable=True, comment='Only via explicit re-subscription (CMPY-03)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_suppressions_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_suppressions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_event_id'], ['email_events.id'], name=op.f('fk_suppressions_email_event_id_email_events'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppressions'))
    )
    op.create_index('ix_suppressions_account_id_email', 'suppressions', ['account_id', 'email'], unique=False)
    op.create_index('ix_suppressions_email_event_id', 'suppressions', ['email_event_id'], unique=False, postgresql_where=sa.text('email_event_id IS NOT NULL'))
    op.create_index('uq_suppressions_active_email', 'suppressions', ['account_id', 'email'], unique=True, postgresql_where=sa.text('lifted_at IS NULL'))
    # ### end Alembic commands ###

    # Opt-out protection triggers (app/db/triggers.py) - not autogenerated.
    for statement in TRIGGER_DDL:
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema."""
    for statement in DROP_DDL:
        op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_suppressions_active_email', table_name='suppressions', postgresql_where=sa.text('lifted_at IS NULL'))
    op.drop_index('ix_suppressions_email_event_id', table_name='suppressions', postgresql_where=sa.text('email_event_id IS NOT NULL'))
    op.drop_index('ix_suppressions_account_id_email', table_name='suppressions')
    op.drop_table('suppressions')
    op.drop_index('ix_subscription_events_subscriber_id_occurred_at', table_name='subscription_events')
    op.drop_index('ix_subscription_events_message_id', table_name='subscription_events', postgresql_where=sa.text('message_id IS NOT NULL'))
    op.drop_index('ix_subscription_events_list_id', table_name='subscription_events', postgresql_where=sa.text('list_id IS NOT NULL'))
    op.drop_index('ix_subscription_events_campaign_id', table_name='subscription_events', postgresql_where=sa.text('campaign_id IS NOT NULL'))
    op.drop_index('ix_subscription_events_account_id_occurred_at', table_name='subscription_events')
    op.drop_table('subscription_events')
    op.drop_index('uq_email_events_provider_event_id', table_name='email_events')
    op.drop_index('ix_email_events_message_id', table_name='email_events')
    op.drop_index('ix_email_events_link_id', table_name='email_events', postgresql_where=sa.text('link_id IS NOT NULL'))
    op.drop_index('ix_email_events_campaign_id_event_type', table_name='email_events')
    op.drop_index('ix_email_events_account_id_event_type_occurred_at', table_name='email_events')
    op.drop_table('email_events')
    op.drop_index('uq_email_messages_provider_message_id', table_name='email_messages', postgresql_where=sa.text('provider_message_id IS NOT NULL'))
    op.drop_index('uq_email_messages_enrollment_id_step_id', table_name='email_messages', postgresql_where=sa.text('enrollment_id IS NOT NULL'))
    op.drop_index('uq_email_messages_campaign_recipient_id', table_name='email_messages', postgresql_where=sa.text('campaign_recipient_id IS NOT NULL'))
    op.drop_index('ix_email_messages_subscriber_id', table_name='email_messages')
    op.drop_index('ix_email_messages_pending', table_name='email_messages', postgresql_where=sa.text("status IN ('queued', 'submitting')"))
    op.drop_index('ix_email_messages_campaign_id_status', table_name='email_messages')
    op.drop_index('ix_email_messages_automation_step_id', table_name='email_messages', postgresql_where=sa.text('automation_step_id IS NOT NULL'))
    op.drop_index('ix_email_messages_automation_id', table_name='email_messages', postgresql_where=sa.text('automation_id IS NOT NULL'))
    op.drop_index('ix_email_messages_account_id_queued_at', table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index('uq_campaign_recipients_campaign_id_email', table_name='campaign_recipients')
    op.drop_index('ix_campaign_recipients_subscriber_id', table_name='campaign_recipients')
    op.drop_index('ix_campaign_recipients_campaign_id_status', table_name='campaign_recipients')
    op.drop_table('campaign_recipients')
    op.drop_index(op.f('ix_test_sends_campaign_id'), table_name='test_sends')
    op.drop_table('test_sends')
    op.drop_table('campaign_stats')
    op.drop_index('ix_campaign_links_campaign_id', table_name='campaign_links')
    op.drop_table('campaign_links')
    op.drop_index('ix_campaign_audiences_tag_id', table_name='campaign_audiences', postgresql_where=sa.text('tag_id IS NOT NULL'))
    op.drop_index('ix_campaign_audiences_subscriber_id', table_name='campaign_audiences', postgresql_where=sa.text('subscriber_id IS NOT NULL'))
    op.drop_index('ix_campaign_audiences_segment_id', table_name='campaign_audiences', postgresql_where=sa.text('segment_id IS NOT NULL'))
    op.drop_index('ix_campaign_audiences_list_id', table_name='campaign_audiences', postgresql_where=sa.text('list_id IS NOT NULL'))
    op.drop_index('ix_campaign_audiences_campaign_id', table_name='campaign_audiences')
    op.drop_table('campaign_audiences')
    op.drop_index('uq_automation_enrollments_automation_id_subscriber_id', table_name='automation_enrollments')
    op.drop_index('ix_automation_enrollments_subscriber_id', table_name='automation_enrollments')
    op.drop_index('ix_automation_enrollments_due', table_name='automation_enrollments', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_automation_enrollments_current_step_id', table_name='automation_enrollments')
    op.drop_table('automation_enrollments')
    op.drop_index('ix_campaigns_topic_list_id', table_name='campaigns', postgresql_where=sa.text('topic_list_id IS NOT NULL'))
    op.drop_index('ix_campaigns_due', table_name='campaigns', postgresql_where=sa.text("status = 'scheduled'"))
    op.drop_index('ix_campaigns_account_id_status', table_name='campaigns')
    op.drop_index('ix_campaigns_account_id_created_at', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('uq_automation_steps_automation_id_position', table_name='automation_steps')
    op.drop_table('automation_steps')
    op.drop_index('ix_templates_account_id_name', table_name='templates')
    op.drop_table('templates')
    op.drop_index('ix_import_row_errors_import_job_id', table_name='import_row_errors')
    op.drop_table('import_row_errors')
    op.drop_index('uq_import_column_mappings_job_id_column_index', table_name='import_column_mappings')
    op.drop_table('import_column_mappings')
    op.drop_index('ix_automations_active_trigger_tag', table_name='automations', postgresql_where=sa.text("status = 'active' AND trigger_tag_id IS NOT NULL"))
    op.drop_index('ix_automations_active_trigger_list', table_name='automations', postgresql_where=sa.text("status = 'active' AND trigger_list_id IS NOT NULL"))
    op.drop_index('ix_automations_account_id_status', table_name='automations')
    op.drop_table('automations')
    op.drop_index('ix_user_sessions_user_id_active', table_name='user_sessions', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('user_sessions')
    op.drop_index('uq_user_identities_issuer_subject', table_name='user_identities')
    op.drop_index('ix_user_identities_user_id', table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_index('ix_subscriber_tags_tag_id', table_name='subscriber_tags')
    op.drop_table('subscriber_tags')
    op.drop_index('ix_subscriber_field_values_field_id_value_text', table_name='subscriber_field_values')
    op.drop_table('subscriber_field_values')
    op.drop_index('uq_senders_account_id_from_email', table_name='senders')
    op.drop_table('senders')
    op.drop_index('uq_segments_account_id_name', table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_media_assets_account_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index('ix_list_memberships_subscriber_id', table_name='list_memberships')
    op.drop_index('ix_list_memberships_list_id_active', table_name='list_memberships', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('list_memberships')
    op.drop_index('ix_import_jobs_pending', table_name='import_jobs', postgresql_where=sa.text("status IN ('queued', 'processing')"))
    op.drop_index('ix_import_jobs_account_id_created_at', table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index('uq_content_blocks_default_per_kind', table_name='content_blocks', postgresql_where=sa.text('is_default AND deleted_at IS NULL'))
    op.drop_index('ix_content_blocks_account_id_kind', table_name='content_blocks')
    op.drop_table('content_blocks')
    op.drop_index('ix_auth_tokens_user_id_purpose', table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index('ix_users_account_id', table_name='users')
    op.drop_table('users')
    op.drop_index('uq_tags_account_id_name', table_name='tags')
    op.drop_table('tags')
    op.drop_index('uq_subscribers_account_id_email', table_name='subscribers')
    op.drop_index('ix_subscribers_account_id_status', table_name='subscribers')
    op.drop_index('ix_subscribers_account_id_external_id', table_name='subscribers')
    op.drop_index('ix_subscribers_account_id_created_at', table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index('uq_sending_domains_account_id_domain', table_name='sending_domains')
    op.drop_table('sending_domains')
    op.drop_index('uq_lists_account_id_name', table_name='lists')
    op.drop_table('lists')
    op.drop_index('uq_custom_fields_account_id_field_key', table_name='custom_fields')
    op.drop_table('custom_fields')
    op.drop_table('accounts')
    # ### end Alembic commands ###

    for enum_name in _ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name} CASCADE")
